### ISSUE TITLE
crash on some specific hpp input

### ISSUE THREAD

**Issue by andiwand** [paulgessinger/codereport#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/codereport", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/codereport/cli.py", line 28, in main
    report_from_json(
  File "/usr/local/lib/python3.8/dist-packages/codereport/util.py", line 47, in report_from_json
    cp.render(dest)
  File "/usr/local/lib/python3.8/dist-packages/codereport/codereport.py", line 73, in render
    f.write(self._render_code_file(sf))
  File "/usr/local/lib/python3.8/dist-packages/codereport/codereport.py", line 92, in _render_code_file
    lexer = _get_lexer(srcfile, raw_content)
  File "/usr/local/lib/python3.8/dist-packages/codereport/codereport.py", line 27, in _get_lexer
    return lexer
UnboundLocalError: local variable 'lexer' referenced before assignment
```

[artifacts.zip](https://github.com/paulgessinger/codereport/files/9997469/artifacts.zip)

https://github.com/acts-project/acts/pull/1662

https://gitlab.cern.ch/acts/ci-bridge/-/jobs/25790677

**Comment by paulgessinger** [comment]
Hm, that's odd.

**Comment by paulgessinger** [comment]
`-Werror,-Wunused-but-set-variable` as an error that pops up is also somewhat strange. What does that mean?
